/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simple;


//import org.junit.jupiter.api.Test;
//
//import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.Test;
import static org.junit.Assert.*;
 

import java.util.logging.Logger;



public class LibraryTest {
	
	Logger logger = Logger.getLogger("LibraryTest");
	
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        logger.info("invoking testSomeLibraryMethod");
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
        //assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    
    @Test public void testAnotherTestMethod() {
    	logger.info("invoking testAnotherTestMethod");
    	assertTrue("anotherTestMethod should return 'true'", Library.class.equals(Library.class));
    	//assertTrue(Library.class.equals(Library.class), "anotherTestMethod should return 'true'");
    }
}
